# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=100)),
                ('pro_desc', models.TextField(max_length=200)),
                ('pro_cat', models.CharField(max_length=100)),
                ('pro_brand', models.CharField(max_length=100)),
                ('pro_image', models.CharField(max_length=100)),
                ('pro_price', models.IntegerField()),
            ],
        ),
    ]
